title: Alexander McIntosh
author:
  name: Alexander McIntosh
  email: mcintalmo@gmail.com

theme: jekyll-theme-minimal

description: >
  Welcome to the beginning of Alexander McIntosh's personal site. A collection
  of blogs, data science projects, and video game development.

header_pages:
  - about.md

social_links:
  - platform: github
    user_url: "https://github.com/mcintalmo"
  - platform: linkedin
    user_url: "https://www.linkedin.com/in/mcintalmo"