title: Alexander McIntosh
author: alex-mcintosh

description: >
  Welcome to the beginning of Alexander McIntosh's personal site. A collection
  of blogs, data science projects, and video game development.

baseurl: ""
url: ""

plugins:
  - jekyll-feed

header_pages:
  - about.md

remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - { platform: github,   user_url: "https://github.com/mcintalmo" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/mcintalmo" }
