title: Alexander McIntosh
author:
  name: Alexander McIntosh
  email: "mcintalmo@gmail.com"

description: >
  Alexander McIntosh's resume website.

baseurl: ""
url: ""

plugins:
  - jekyll-feed

header_pages:
  - resume.md
  - credentials.md

remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - { platform: github,   user_url: "https://github.com/mcintalmo" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/mcintalmo" }
