services:

  agent:
    build:
      context: ../backend
      dockerfile: ./agent/Dockerfile
    network_mode: host
    restart: always
    env_file:
      - ../backend/.env
    environment:
      - LIVEKIT_URL=ws://localhost:7880
      - PYTHONPATH=agent/src
    depends_on:
      - livekit
      - whisper
      - kokoro

  auth:
    build:
      context: ../backend
      dockerfile: ./auth/Dockerfile
    network_mode: host
    restart: always
    env_file:
      - ../backend/.env
    environment:
      - PYTHONPATH=auth/src

  livekit:
    image: livekit/livekit-server:latest
    command: --config /livekit.yaml
    volumes:
      - ./livekit.yaml:/livekit.yaml
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
      - "8080:8080"
    restart: always
    env_file:
      - ../backend/.env
    environment:
      - LIVEKIT_KEYS="${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET}"


  whisper:
    image: fedirz/faster-whisper-server:latest-cpu
    environment:
      # Automatically downloads the model on first boot
      - WHISPER__MODEL=Systran/faster-whisper-tiny.en 
    volumes:
      - ./models:/root/.cache/huggingface
    ports:
      - "10300:8000"
    restart: always

  kokoro:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:latest
    ports:
      - "8880:8880"
    volumes:
      - ./kokoro_cache:/app/cache
    restart: always

  frontend:
    profiles:
      - dev
    build:
      context: ../frontend
      dockerfile: Dockerfile

  mcp:
    profiles:
      - dev
    build:
      context: ../backend
      dockerfile: ./mcp/Dockerfile

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    profiles:
      - telemetry
    volumes:
      - ./observability/otel/otel-collector.yaml:/etc/otel/config.yaml
    command: ["--config=/etc/otel/config.yaml"]
    ports:
      - "4317:4317"   # gRPC
      - "4318:4318"   # HTTP

  jaeger:
    image: jaegertracing/jaeger:latest
    profiles:
      - telemetry
    ports:
      - "16686:16686" # UI
      - "14250:14250" # gRPC from collector

  prometheus:
    image: prom/prometheus:latest
    profiles:
      - telemetry
    volumes:
      - ./observability/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

volumes:
  prometheus_data: