model_list:
  - model_name: portfolio-llm
    litellm_params:
      model: google/gemini-2.5-flash
      custom_llm_provider: openrouter
      api_key: os.environ/OPENROUTER_API_KEY
      max_tokens: 2048
      timeout: 10
      extra_body:
        provider:
          zdr: true
          data_collection: "deny"

  - model_name: portfolio-llm-local
    litellm_params:
      model: openai/qwen2.5:3b
      api_base: http://localhost:11434/v1
      api_key: ollama
      timeout: 60

  - model_name: portfolio-llm-openrouter-gemini
    litellm_params:
      model: google/gemini-2.5-flash
      custom_llm_provider: openrouter
      api_key: os.environ/OPENROUTER_API_KEY
      max_tokens: 2048
      timeout: 10
      extra_body:
        provider:
          zdr: true
          data_collection: "deny"

router_settings:
  num_retries: 2
  fallbacks:
    - portfolio-llm:
        [
          "portfolio-llm-local",
        ]
  cooldown_time: 10
  allowed_fails: 1

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
