receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp/phoenix:
    endpoint: phoenix:4317
    tls:
      insecure: true
      
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
      
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger, otlp/phoenix]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]


